import type { Metadata } from "next";
import { Jost } from "next/font/google";
import "./globals.css";
import TopNavbar from './TopNavbar';

const jost = Jost({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={jost.className}>
        <div className="min-h-screen bg-[#FCFAF2] font-[Jost] text-[#000]">
          <TopNavbar />
          {children}
        </div>
      </body>
    </html>
  );
}